#!/usr/bin/env bash
cd "$(dirname "$0")" || exit 1
run()     { snabb/src/snabb lisper -c lisper${LISP_N}.conf; }
start()   { LISPER_DEBUG=1 run > lisper${LISP_N}.log & }
stop()    { pgrep -f "snabb lisper -c lisper${LISP_N}" | xargs kill -9; }
restart() { stop; start; }
if [ "$1" ]; then $1; else stop; run; fi
