-- Linux error messages

return {
  [1] = "Operation not permitted",	 -- PERM
  [2] = "No such file or directory",	 -- NOENT
  [3] = "No such process",	 -- SRCH
  [4] = "Interrupted system call",	 -- INTR
  [5] = "Input/output error",	 -- IO
  [6] = "No such device or address",	 -- NXIO
  [7] = "Argument list too long",	 -- 2BIG
  [8] = "Exec format error",	 -- NOEXEC
  [9] = "Bad file descriptor",	 -- BADF
  [10] = "No child processes",	 -- CHILD
  [11] = "Resource temporarily unavailable",	 -- AGAIN
  [12] = "Cannot allocate memory",	 -- NOMEM
  [13] = "Permission denied",	 -- ACCES
  [14] = "Bad address",	 -- FAULT
  [15] = "Block device required",	 -- NOTBLK
  [16] = "Device or resource busy",	 -- BUSY
  [17] = "File exists",	 -- EXIST
  [18] = "Invalid cross-device link",	 -- XDEV
  [19] = "No such device",	 -- NODEV
  [20] = "Not a directory",	 -- NOTDIR
  [21] = "Is a directory",	 -- ISDIR
  [22] = "Invalid argument",	 -- INVAL
  [23] = "Too many open files in system",	 -- NFILE
  [24] = "Too many open files",	 -- MFILE
  [25] = "Inappropriate ioctl for device",	 -- NOTTY
  [26] = "Text file busy",	 -- TXTBSY
  [27] = "File too large",	 -- FBIG
  [28] = "No space left on device",	 -- NOSPC
  [29] = "Illegal seek",	 -- SPIPE
  [30] = "Read-only file system",	 -- ROFS
  [31] = "Too many links",	 -- MLINK
  [32] = "Broken pipe",	 -- PIPE
  [33] = "Numerical argument out of domain",	 -- DOM
  [34] = "Numerical result out of range",	 -- RANGE
  [35] = "Resource deadlock avoided",	 -- DEADLK
  [36] = "File name too long",	 -- NAMETOOLONG
  [37] = "No locks available",	 -- NOLCK
  [38] = "Function not implemented",	 -- NOSYS
  [39] = "Directory not empty",	 -- NOTEMPTY
  [40] = "Too many levels of symbolic links",	 -- LOOP
  [42] = "No message of desired type",	 -- NOMSG
  [43] = "Identifier removed",	 -- IDRM
  [44] = "Channel number out of range",	 -- CHRNG
  [45] = "Level 2 not synchronized",	 -- L2NSYNC
  [46] = "Level 3 halted",	 -- L3HLT
  [47] = "Level 3 reset",	 -- L3RST
  [48] = "Link number out of range",	 -- LNRNG
  [49] = "Protocol driver not attached",	 -- UNATCH
  [50] = "No CSI structure available",	 -- NOCSI
  [51] = "Level 2 halted",	 -- L2HLT
  [52] = "Invalid exchange",	 -- BADE
  [53] = "Invalid request descriptor",	 -- BADR
  [54] = "Exchange full",	 -- XFULL
  [55] = "No anode",	 -- NOANO
  [56] = "Invalid request code",	 -- BADRQC
  [57] = "Invalid slot",	 -- BADSLT
  [59] = "Bad font file format",	 -- BFONT
  [60] = "Device not a stream",	 -- NOSTR
  [61] = "No data available",	 -- NODATA
  [62] = "Timer expired",	 -- TIME
  [63] = "Out of streams resources",	 -- NOSR
  [64] = "Machine is not on the network",	 -- NONET
  [65] = "Package not installed",	 -- NOPKG
  [66] = "Object is remote",	 -- REMOTE
  [67] = "Link has been severed",	 -- NOLINK
  [68] = "Advertise error",	 -- ADV
  [69] = "Srmount error",	 -- SRMNT
  [70] = "Communication error on send",	 -- COMM
  [71] = "Protocol error",	 -- PROTO
  [72] = "Multihop attempted",	 -- MULTIHOP
  [73] = "RFS specific error",	 -- DOTDOT
  [74] = "Bad message",	 -- BADMSG
  [75] = "Value too large for defined data type",	 -- OVERFLOW
  [76] = "Name not unique on network",	 -- NOTUNIQ
  [77] = "File descriptor in bad state",	 -- BADFD
  [78] = "Remote address changed",	 -- REMCHG
  [79] = "Can not access a needed shared library",	 -- LIBACC
  [80] = "Accessing a corrupted shared library",	 -- LIBBAD
  [81] = ".lib section in a.out corrupted",	 -- LIBSCN
  [82] = "Attempting to link in too many shared libraries",	 -- LIBMAX
  [83] = "Cannot exec a shared library directly",	 -- LIBEXEC
  [84] = "Invalid or incomplete multibyte or wide character",	 -- ILSEQ
  [85] = "Interrupted system call should be restarted",	 -- RESTART
  [86] = "Streams pipe error",	 -- STRPIPE
  [87] = "Too many users",	 -- USERS
  [88] = "Socket operation on non-socket",	 -- NOTSOCK
  [89] = "Destination address required",	 -- DESTADDRREQ
  [90] = "Message too long",	 -- MSGSIZE
  [91] = "Protocol wrong type for socket",	 -- PROTOTYPE
  [92] = "Protocol not available",	 -- NOPROTOOPT
  [93] = "Protocol not supported",	 -- PROTONOSUPPORT
  [94] = "Socket type not supported",	 -- SOCKTNOSUPPORT
  [95] = "Operation not supported",	 -- NOTSUP
  [96] = "Protocol family not supported",	 -- PFNOSUPPORT
  [97] = "Address family not supported by protocol",	 -- AFNOSUPPORT
  [98] = "Address already in use",	 -- ADDRINUSE
  [99] = "Cannot assign requested address",	 -- ADDRNOTAVAIL
  [100] = "Network is down",	 -- NETDOWN
  [101] = "Network is unreachable",	 -- NETUNREACH
  [102] = "Network dropped connection on reset",	 -- NETRESET
  [103] = "Software caused connection abort",	 -- CONNABORTED
  [104] = "Connection reset by peer",	 -- CONNRESET
  [105] = "No buffer space available",	 -- NOBUFS
  [106] = "Transport endpoint is already connected",	 -- ISCONN
  [107] = "Transport endpoint is not connected",	 -- NOTCONN
  [108] = "Cannot send after transport endpoint shutdown",	 -- SHUTDOWN
  [109] = "Too many references: cannot splice",	 -- TOOMANYREFS
  [110] = "Connection timed out",	 -- TIMEDOUT
  [111] = "Connection refused",	 -- CONNREFUSED
  [112] = "Host is down",	 -- HOSTDOWN
  [113] = "No route to host",	 -- HOSTUNREACH
  [114] = "Operation already in progress",	 -- ALREADY
  [115] = "Operation now in progress",	 -- INPROGRESS
  [116] = "Stale NFS file handle",	 -- STALE
  [117] = "Structure needs cleaning",	 -- UCLEAN
  [118] = "Not a XENIX named type file",	 -- NOTNAM
  [119] = "No XENIX semaphores available",	 -- NAVAIL
  [120] = "Is a named type file",	 -- ISNAM
  [121] = "Remote I/O error",	 -- REMOTEIO
  [122] = "Disk quota exceeded",	 -- DQUOT
  [123] = "No medium found",	 -- NOMEDIUM
  [124] = "Wrong medium type",	 -- MEDIUMTYPE
  [125] = "Operation canceled",	 -- CANCELED
  [126] = "Required key not available",	 -- NOKEY
  [127] = "Key has expired",	 -- KEYEXPIRED
  [128] = "Key has been revoked",	 -- KEYREVOKED
  [129] = "Key was rejected by service",	 -- KEYREJECTED
  [130] = "Owner died",	 -- OWNERDEAD
  [131] = "State not recoverable",	 -- NOTRECOVERABLE
  [132] = "Operation not possible due to RF-kill",	 -- RFKILL
}

