Usage: run-nohw --help
       run-nohw --bt PATH --conf PATH --b4-if NAME --inet-if NAME [--verbose]

       --bt, -b PATH        Path to the file containing the binding table.
       --conf, -c PATH      Path to the lwAFTR configuration file.
       --b4-if, -B NAME     Name of the B4-side network interface.
       --inet-if, -I NAME   Name of the Internet-side network interface.
       --verbose, -v        Be verbose. Can be used multiple times.
       --help, -h           Show this help message.
