#!/bin/bash
if [ $# != 1 ]; then
    echo "Usage: maketraces <dir>" >&2
    exit 1
fi
set -e
cd $1
exec luajit -e "package.path = package.path .. \";$SNABB/src/lua/?.lua\"" \
            $SNABB/src/lua/maketraces.lua "$@"

