#!/usr/bin/env bash
run()     { ip netns exec node${LISP_N} ./lisp.lua ${LISP_N}; }
start()   { run >lisp${LISP_N}.log & }
stop()    { pgrep -f "lisp.lua ${LISP_N}" | xargs kill -9; }
restart() { stop; start; }
if [ "$1" ]; then $1; else stop; run; fi
