#!/usr/bin/env bash

appnodes="1 2 5 6"
lispnodes="4 8"
nodes="$appnodes $lispnodes"

bringup() {

ip netns add r2
ip netns exec r2 sysctl -wq net.ipv6.conf.all.forwarding=1

for n in $nodes; do
    ip netns add node$n
    ip link add netns node$n e0 address 00:00:00:00:01:0$n type veth peer name e$n netns r2 address 00:00:00:00:00:0$n
    ip netns exec r2 ip addr add fd80:$n::1/56 dev e$n
    ip netns exec node$n ip addr add fd80:$n::2/56 dev e0
    ip netns exec node$n ip -6 route add default via fd80:$n::1
    ip netns exec node$n ip link set e0 up
    ip netns exec r2 ip link set e$n up
done

eth() {
local p="$1"
local n="$2"
ip link add netns node$p e$n address 00:00:00:00:01:0$n type veth peer name t$n netns node$p address 00:00:00:00:aa:0$n
ip netns exec node$p ip addr add 10.0.0.$n/24 dev t$n
ip netns exec node$p ip link set e$n up
ip netns exec node$p ip link set t$n up
}
eth 4 3
eth 8 7

for n in $appnodes; do
    ip netns exec node$n tunctl -t t0
    ip netns exec node$n ip link set address 00:00:00:00:aa:0$n dev t0
    ip netns exec node$n ifconfig t0 10.0.0.$n/24 mtu 1400 up
    ./l2tp.app$n start
done

for n in $lispnodes; do
    ./lisp$n start
    ./lisper$n start
done
}

teardown() {

for n in $appnodes; do
    ./l2tp.app$n stop
done

for n in $lispnodes; do
    ./lisp$n stop
    ./lisper$n stop
done

for n in $nodes; do
    ip netns del node$n
done

ip netns del r2
}

if [ "$1" ]; then $1; else bringup; fi
