#!/usr/bin/env bash

# Use this test mode if you have two pairs of Intel10G cards
# with loopback cables between cards 1,2 and 3,4.
# Give the names and pci addresses of the interfaces below.

export intel1=enp5s0f0
export intel2=enp5s0f1
export intel3=enp7s0f0
export intel4=enp7s0f1
export intel1_pci=0000:05:00.0
export intel2_pci=0000:05:00.1
export intel3_pci=0000:07:00.0
export intel4_pci=0000:07:00.1

./testnet bringup
