#!../../snabb snsh
local intel = require("apps.intel1g.intel1g")
local pci0 = os.getenv("SNABB_PCI_INTEL1G0")
local pci1 = os.getenv("SNABB_PCI_INTEL1G1")
local nic = intel.Intel1g:new({ pciaddr = pci0 })
local tab = nic:redirection_table()
assert(#tab == 0)
assert(tab[0])
local nic0 = intel.Intel1g:new({pciaddr = pci0, rxq = 0})
local nic1 = intel.Intel1g:new({pciaddr = pci0, rxq = 1})
tab = nic:redirection_table()
assert(#tab == 1)
assert(tab[0])
assert(tab[1])

local nic2 = intel.Intel1g:new({pciaddr = pci0, rxq = 2})
local nic3 = intel.Intel1g:new({pciaddr = pci0, rxq = 3})
tab = nic:redirection_table()
assert(#tab == 3)
assert(tab[2])
assert(tab[3])
os.exit(0)
