-- OSX error messages

return {
  [1] = "Operation not permitted",	 -- PERM
  [2] = "No such file or directory",	 -- NOENT
  [3] = "No such process",	 -- SRCH
  [4] = "Interrupted system call",	 -- INTR
  [5] = "Input/output error",	 -- IO
  [6] = "Device not configured",	 -- NXIO
  [7] = "Argument list too long",	 -- 2BIG
  [8] = "Exec format error",	 -- NOEXEC
  [9] = "Bad file descriptor",	 -- BADF
  [10] = "No child processes",	 -- CHILD
  [11] = "Resource deadlock avoided",	 -- DEADLK
  [12] = "Cannot allocate memory",	 -- NOMEM
  [13] = "Permission denied",	 -- ACCES
  [14] = "Bad address",	 -- FAULT
  [15] = "Block device required",	 -- NOTBLK
  [16] = "Resource busy",	 -- BUSY
  [17] = "File exists",	 -- EXIST
  [18] = "Cross-device link",	 -- XDEV
  [19] = "Operation not supported by device",	 -- NODEV
  [20] = "Not a directory",	 -- NOTDIR
  [21] = "Is a directory",	 -- ISDIR
  [22] = "Invalid argument",	 -- INVAL
  [23] = "Too many open files in system",	 -- NFILE
  [24] = "Too many open files",	 -- MFILE
  [25] = "Inappropriate ioctl for device",	 -- NOTTY
  [26] = "Text file busy",	 -- TXTBSY
  [27] = "File too large",	 -- FBIG
  [28] = "No space left on device",	 -- NOSPC
  [29] = "Illegal seek",	 -- SPIPE
  [30] = "Read-only file system",	 -- ROFS
  [31] = "Too many links",	 -- MLINK
  [32] = "Broken pipe",	 -- PIPE
  [33] = "Numerical argument out of domain",	 -- DOM
  [34] = "Result too large",	 -- RANGE
  [35] = "Resource temporarily unavailable",	 -- AGAIN
  [36] = "Operation now in progress",	 -- INPROGRESS
  [37] = "Operation already in progress",	 -- ALREADY
  [38] = "Socket operation on non-socket",	 -- NOTSOCK
  [39] = "Destination address required",	 -- DESTADDRREQ
  [40] = "Message too long",	 -- MSGSIZE
  [41] = "Protocol wrong type for socket",	 -- PROTOTYPE
  [42] = "Protocol not available",	 -- NOPROTOOPT
  [43] = "Protocol not supported",	 -- PROTONOSUPPORT
  [44] = "Socket type not supported",	 -- SOCKTNOSUPPORT
  [46] = "Protocol family not supported",	 -- PFNOSUPPORT
  [47] = "Address family not supported by protocol family",	 -- AFNOSUPPORT
  [48] = "Address already in use",	 -- ADDRINUSE
  [49] = "Can't assign requested address",	 -- ADDRNOTAVAIL
  [50] = "Network is down",	 -- NETDOWN
  [51] = "Network is unreachable",	 -- NETUNREACH
  [52] = "Network dropped connection on reset",	 -- NETRESET
  [53] = "Software caused connection abort",	 -- CONNABORTED
  [54] = "Connection reset by peer",	 -- CONNRESET
  [55] = "No buffer space available",	 -- NOBUFS
  [56] = "Socket is already connected",	 -- ISCONN
  [57] = "Socket is not connected",	 -- NOTCONN
  [58] = "Can't send after socket shutdown",	 -- SHUTDOWN
  [59] = "Too many references: can't splice",	 -- TOOMANYREFS
  [60] = "Operation timed out",	 -- TIMEDOUT
  [61] = "Connection refused",	 -- CONNREFUSED
  [62] = "Too many levels of symbolic links",	 -- LOOP
  [63] = "File name too long",	 -- NAMETOOLONG
  [64] = "Host is down",	 -- HOSTDOWN
  [65] = "No route to host",	 -- HOSTUNREACH
  [66] = "Directory not empty",	 -- NOTEMPTY
  [67] = "Too many processes",	 -- PROCLIM
  [68] = "Too many users",	 -- USERS
  [69] = "Disc quota exceeded",	 -- DQUOT
  [70] = "Stale NFS file handle",	 -- STALE
  [71] = "Too many levels of remote in path",	 -- REMOTE
  [72] = "RPC struct is bad",	 -- BADRPC
  [73] = "RPC version wrong",	 -- RPCMISMATCH
  [74] = "RPC prog. not avail",	 -- PROGUNAVAIL
  [75] = "Program version wrong",	 -- PROGMISMATCH
  [76] = "Bad procedure for program",	 -- PROCUNAVAIL
  [77] = "No locks available",	 -- NOLCK
  [78] = "Function not implemented",	 -- NOSYS
  [79] = "Inappropriate file type or format",	 -- FTYPE
  [80] = "Authentication error",	 -- AUTH
  [81] = "Need authenticator",	 -- NEEDAUTH
  [84] = "Value too large to be stored in data type",	 -- OVERFLOW
  [85] = "Bad executable (or shared library)",	 -- BADEXEC
  [86] = "Bad CPU type in executable",	 -- BADARCH
  [87] = "Shared library version mismatch",	 -- SHLIBVERS
  [88] = "Malformed Mach-o file",	 -- BADMACHO
  [89] = "Operation canceled",	 -- CANCELED
  [90] = "Identifier removed",	 -- IDRM
  [91] = "No message of desired type",	 -- NOMSG
  [92] = "Illegal byte sequence",	 -- ILSEQ
  [93] = "Attribute not found",	 -- NOATTR
  [94] = "Bad message",	 -- BADMSG
  [95] = "EMULTIHOP (Reserved)",	 -- MULTIHOP
  [96] = "No message available on STREAM",	 -- NODATA
  [97] = "ENOLINK (Reserved)",	 -- NOLINK
  [98] = "No STREAM resources",	 -- NOSR
  [99] = "Not a STREAM",	 -- NOSTR
  [100] = "Protocol error",	 -- PROTO
  [101] = "STREAM ioctl timeout",	 -- TIME
  [102] = "Operation not supported on socket",	 -- OPNOTSUPP
  [103] = "Policy not found",	 -- NOPOLICY
  [104] = "State not recoverable",	 -- NOTRECOVERABLE
  [105] = "Previous owner died",	 -- OWNERDEAD
  [106] = "Interface output queue is full",	 -- QFULL
}

