#!/usr/bin/env bash
cd "$(dirname "$0")" || exit 1
run()     { ./baseline.lua; }
start()   { run & }
stop()    { pgrep -f "baseline.lua" | xargs kill -9; }
restart() { stop; start; }
if [ "$1" ]; then $1; else stop; run; fi
