#!/usr/bin/env bash
set -e
out=$(program/snabbnfv/selftest.sh bench 1500 \
    program/snabbnfv/test_fixtures/nfvconfig/test_functions/crypto-tunnel.ports)
# Extract floating point Gbits number from output.
echo "$out" | grep IPERF-1500 | cut -d " " -f 2
