#!/usr/bin/env bash
set -e
export SNABB_IPERF_BENCH_CONF=program/snabbnfv/test_fixtures/nfvconfig/test_functions/crypto-tunnel.ports
out=$(program/snabbnfv/selftest.sh bench 1500)
# Extract floating point Gbits number from output.
echo "$out" | grep IPERF-1500 | cut -d " " -f 2
