Document: snabbswitch
Title: Debian snabbswitch Manual
Author: <insert document author here>
Abstract: This manual describes what snabbswitch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/snabbswitch/snabbswitch.sgml.gz

Format: postscript
Files: /usr/share/doc/snabbswitch/snabbswitch.ps.gz

Format: text
Files: /usr/share/doc/snabbswitch/snabbswitch.text.gz

Format: HTML
Index: /usr/share/doc/snabbswitch/html/index.html
Files: /usr/share/doc/snabbswitch/html/*.html
