#! /bin/sh

exec qemu-system-x86_64 -enable-kvm \
	-M pc-q35-2.0 \
	-drive file=openwrt.img,id=d0,if=none \
	-device ide-hd,drive=d0,bus=ide.0 \
	-netdev tap,ifname=olan,script=./tap-b4,downscript=./tap-b4-down,id=hn0 \
	-device e1000,netdev=hn0,id=nic1 \
	-netdev tap,ifname=aftr,script=./tap-b4,downscript=./tap-b4-down,id=hn1 \
	-device e1000,netdev=hn1,id=nic2 \
	-serial mon:stdio -nographic
