-- error messages
-- we could get these from libc strerror, but aalows eg localisation, and makes things clearer. Only loaded if you use them.

local E = require("syscall.constants").E

local msg = {
  ILSEQ      = "Illegal byte sequence", 
  DOM        = "Domain error", 
  RANGE      = "Result not representable", 

  NOTTY      = "Not a tty", 
  ACCES      = "Permission denied", 
  PERM       = "Operation not permitted", 
  NOENT      = "No such file or directory", 
  SRCH       = "No such process", 
  EXIST      = "File exists", 

  OVERFLOW   = "Value too large for data type", 
  NOSPC      = "No space left on device", 
  NOMEM      = "Out of memory", 

  BUSY       = "Resource busy", 
  INTR       = "Interrupted system call", 
  AGAIN      = "Resource temporarily unavailable", 
  SPIPE      = "Invalid seek", 

  XDEV       = "Cross-device link", 
  ROFS       = "Read-only file system", 
  NOTEMPTY   = "Directory not empty", 

  CONNRESET  = "Connection reset by peer", 
  TIMEDOUT   = "Operation timed out", 
  CONNREFUSED= "Connection refused", 
  HOSTDOWN   = "Host is down", 
  HOSTUNREACH= "Host is unreachable", 
  ADDRINUSE  = "Address in use", 

  PIPE       = "Broken pipe", 
  IO         = "I/O error", 
  NXIO       = "No such device or address", 
  NOTBLK     = "Block device required", 
  NODEV      = "No such device", 
  NOTDIR     = "Not a directory", 
  ISDIR      = "Is a directory", 
  TXTBSY     = "Text file busy", 
  NOEXEC     = "Exec format error", 

  INVAL      = "Invalid argument", 

  ["2BIG"]   = "Argument list too long", 
  LOOP       = "Symbolic link loop", 
  NAMETOOLONG= "Filename too long", 
  NFILE      = "Too many open files in system", 
  MFILE      = "No file descriptors available", 
  BADF       = "Bad file descriptor", 
  CHILD      = "No child process", 
  FAULT      = "Bad address", 
  FBIG       = "File too large", 
  MLINK      = "Too many links", 
  NOLCK      = "No locks available", 

  DEADLK     = "Resource deadlock would occur", 
  NOTRECOVERABLE="State not recoverable", 
  OWNERDEAD  = "Previous owner died", 
  CANCELED   = "Operation canceled", 
  NOSYS      = "Function not implemented", 
  NOMSG      = "No message of desired type", 
  IDRM       = "Identifier removed", 
  NOSTR      = "Device not a stream", 
  NODATA     = "No data available", 
  TIME       = "Device timeout", 
  NOSR       = "Out of streams resources", 
  NOLINK     = "Link has been severed", 
  PROTO      = "Protocol error", 
  BADMSG     = "Bad message", 
  BADFD      = "File descriptor in bad state", 
  NOTSOCK    = "Not a socket", 
  DESTADDRREQ= "Destination address required", 
  MSGSIZE    = "Message too large", 
  PROTOTYPE  = "Protocol wrong type for socket", 
  NOPROTOOPT = "Protocol not available", 
  PROTONOSUPPORT="Protocol not supported", 
  SOCKTNOSUPPORT="Socket type not supported", 
  OPNOTSUPP  = "Not supported", 
  PFNOSUPPORT= "Protocol family not supported", 
  AFNOSUPPORT= "Address family not supported by protocol", 
  ADDRNOTAVAIL="Address not available", 
  NETDOWN    = "Network is down", 
  NETUNREACH = "Network unreachable", 
  NETRESET   = "Connection reset by network", 
  CONNABORTED= "Connection aborted", 
  NOBUFS     = "No buffer space available", 
  ISCONN     = "Socket is connected", 
  NOTCONN    = "Socket not connected", 
  SHUTDOWN   = "Cannot send after socket shutdown", 
  ALREADY    = "Operation already in progress", 
  INPROGRESS = "Operation in progress", 
  STALE      = "Stale file handle", 
  REMOTEIO   = "Remote I/O error", 
  DQUOT      = "Quota exceeded", 
  NOMEDIUM   = "No medium found", 
  MEDIUMTYPE = "Wrong medium type",

  L3RST      = "Level 3 reset",
  L3HLT      = "Level 3 halted",
  L2HLT      = "Level 2 halted",
  L2NSYNC    = "Level 2 not synchronized",
  LIBSCN     = ".lib section in a.out corrupted",
  NOTNAM     = "Not a XENIX named type file",
  DOTDOT     = "RFS specific error",
  CHRNG      = "Channel number out of range",
  LNRNG      = "Link number out of range",
  RESTART    = "Interrupted system call should be restarted",
  BADRQC     = "Invalid request code",
  LIBACC     = "Can not access a needed shared library",
  ISNAM      = "Is a named type file",
  COMM       = "Communication error on send",
  ADV        = "Advertise error",
  XFULL      = "Exchange full",
  NAVAIL     = "No XENIX semaphores available",
  TOOMANYREFS= "Too many references: cannot splice",
  USERS      = "Too many users",
  BFONT      = "Bad font file format",
  NOKEY      = "Required key not available",
  KEYREJECTED= "Key was rejected by service",
  KEYEXPIRED = "Key has expired",
  KEYREVOKED = "Key has been revoked",
  REMCHG     = "Remote address changed",
  NOCSI      = "No CSI structure available",
  REMOTE     = "Object is remote",
  BADE       = "Invalid exchange",
  STRPIPE    = "Streams pipe error",
  RFKILL     = "Operation not possible due to RF-kill",
  NOANO      = "No anode",
  NOTUNIQ    = "Name not unique on network",
  LIBEXEC    = "Cannot exec a shared library directly",
  BADR       = "Invalid request descriptor",
  NOPKG      = "Package not installed",
  NONET      = "Machine is not on the network",
  SRMNT      = "Srmount error",
  MULTIHOP   = "Multihop attempted",
  BADSLT     = "Invalid slot",
  UCLEAN     = "Structure needs cleaning",
  LIBBAD     = "Accessing a corrupted shared library",
  LIBMAX     = "Attempting to link in too many shared libraries",
  UNATCH     = "Protocol driver not attached",

-- these are NetBSD specific errors
  PROCLIM    = "Too many processes",
  FTYPE      = "Inappropriate file type or format",
  PROGUNAVAIL= "RPC prog. not avail",
  AUTH       = "Authentication error",
  PROGMISMATCH = "Program version wrong",
  BADRPC     = "RPC struct is bad",
  NEEDAUTH   = "Need authenticator",
  RPCMISMATCH= "RPC version wrong",
  PROCUNAVAIL= "Bad procedure for program",
  NOATTR     = "Attribute not found",
  NOTSUP     = "Not supported",
}

local errors = setmetatable({}, {
  __index = function(err, errno) return "No error information (error " .. errno .. ")" end,
  __call = function(err, errno) return err[errno] end,
})

for k, v in pairs(msg) do
  if E[k] then errors[E[k]] = v end
end

return errors

